[package]
name = "worker"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
colored = "2.1.0"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.10.0", features = ["v4"] }
